# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# selection.py
# Created on: 2019-07-24 15:49:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Outfalls_All_Query = "Outfalls_All_Query"
Outfalls_All_Query__3_ = Outfalls_All_Query
Sewers_All_Query = "Sewers_All_Query"
Outfalls_Selected = "D:\\GIS\\Dewberry\\gdb\\MS4Data.gdb\\Outfalls_Selected"

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(Outfalls_All_Query, "INTERSECT", Sewers_All_Query, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Copy Features
arcpy.CopyFeatures_management(Outfalls_All_Query__3_, Outfalls_Selected, "", "0", "0", "0")

